name: OraxenTransparentBlocks
version: ${project.version}
main: me.playajames.oraxentransparentblocks.OraxenTransparentBlocks
api-version: 1.16
depend: [Oraxen, WorldGuard, WorldEdit]
authors: [playajames]
commands:
  otb:
    description: Reloads OraxenTransparentBlocks plugin.
